# CI de Nível 02 - Disparo programado através de agenda

# nome da pipeline
name: 'Execução Agendada'

# gatilhos ou triggers - regras de disparo
# gatilho programado = schedule + cron
on:
  schedule:
    # cronograma de execução - formato cron
    # 1 - minuto (0-59)
    # 2 - hora (0-23)
    # 3 - dia do mês (1-31)
    # 4 - mês (1-12)
    # 5 - dia da semana (0-7, onde 0 e 7 representam domingo)
    - cron: '*/30 * * * *' # a cada 30 minutos
  # - cron: '0 0 * * 5' -> toda sexta-feira à meia-noite

# tarefas dentro da pipeline = jobs
jobs:
  # nome do job
  e2e-tests:
    # maquina onde o job vai rodar
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, windows]

    # definir os passos do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      # instalação do yarn
      - name: Instalando yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn

      # instalação dos browsers do Playwright
      - name: Instalando browsers do Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando testes e2e
        run: yarn run e2e

        # continue-on-error: garante que o próximo passo (upload do relatório)
        # seja executado mesmo que os testes falhem
        continue-on-error: true

      - name: Relatório HTML do Playwright
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
