# CI de Nível 03 - Disparo após a conclusão de outra pipeline

# nome da pipeline
name: 'Execução por Deploy'

# gatilhos ou triggers - regras de disparo
# gatilho após a conclusão de outra pipeline = workflow_run
on:
  workflow_run:
    # nome da pipeline que deve ser monitorada
    workflows: ['Execução Manual']
    # tipo de evento que deve ocorrer na pipeline monitorada para disparar esta pipeline
    types: 
      - completed

# tarefas dentro da pipeline = jobs
jobs:
  # nome do job
  e2e-tests:
    # maquina onde o job vai rodar
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, windows]

    # definir os passos do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
      
      # instalação do yarn
      - name: Instalando yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn 

      # instalação dos browsers do Playwright
      - name: Instalando browsers do Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando testes e2e
        run: yarn run e2e

      # continue-on-error: garante que o próximo passo (upload do relatório)
      # seja executado mesmo que os testes falhem
        continue-on-error: true


      - name: Relatório HTML do 'Playwright
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30